name: Student_Performance_ML
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - alsa-lib=1.2.14
  - annotated-types=0.7.0
  - asttokens=3.0.1
  - attrs=25.4.0
  - backports.zstd=1.2.0
  - bleach=6.3.0
  - bokeh=3.8.1
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.12.12
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dacite=1.9.2
  - dataclasses=0.8
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - double-conversion=3.3.1
  - executing=2.2.1
  - filetype=1.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.0
  - freetype=2.14.1
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.2.0
  - holoviews=1.22.1
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imagehash=4.3.2
  - importlib-metadata=8.7.0
  - ipykernel=6.31.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyterlab_widgets=3.0.16
  - kagglehub=0.3.13
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang-cpp21.1=21.1.7
  - libclang13=21.1.7
  - libcups=2.3.3
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libllvm21=21.1.7
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.53
  - libpq=18.1
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=3.1.2
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - linkify-it-py=2.0.3
  - llvmlite=0.45.1
  - markdown=3.10
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.2.1
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - minify-html=0.18.1
  - multimethod=1.12
  - munkres=1.1.4
  - narwhals=2.13.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6
  - numba=0.62.1
  - numpy=2.3.5
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - panel=1.8.4
  - param=2.3.1
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.46
  - pexpect=4.9.0
  - phik=0.12.5
  - pillow=12.0.0
  - pixman=0.46.4
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - puremagic=1.30
  - py-xgboost=3.1.2
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyside6=6.9.3
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.12
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyviz_comms=3.0.6
  - pywavelets=1.9.0
  - pyxdg=0.28
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.9.3
  - readline=8.2
  - requests=2.32.5
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - spyder-kernels=3.1.2
  - stack_data=0.6.3
  - statsmodels=0.14.6
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typeguard=4.4.4
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - uc-micro-py=1.0.3
  - unicodedata2=17.0.0
  - urllib3=2.6.0
  - visions=0.8.1
  - wayland=1.24.0
  - wcwidth=0.2.14
  - webencodings=0.5.1
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - wordcloud=1.9.4
  - wurlitzer=3.1.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xyzservices=2025.11.0
  - yaml=0.2.5
  - ydata-profiling=4.18.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - pip==24.3.1
prefix: /home/eddie/miniforge3/envs/Student_Performance_ML
