name: econometrics-env
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - appnope=0.1.4
  - asttokens=3.0.1
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.14.0
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - executing=2.2.1
  - fonttools=4.60.1
  - freetype=2.14.1
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=6.31.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.5.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kagglehub=0.3.13
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcxx=21.1.6
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libpng=1.6.51
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.3.5
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - patsy=1.0.2
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.14.0
  - python-dateutil=2.9.0.post0
  - python-gil=3.14.0
  - python-tzdata=2025.2
  - python_abi=3.14
  - pytz=2025.2
  - pyxdg=0.28
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - readline=8.2
  - requests=2.32.5
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - spyder-kernels=3.1.2
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - wurlitzer=3.1.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7

prefix: "/Users/edmundzhou/miniforge3/envs/econometrics-env"
