name: Student_Performance_ML
channels:
  - conda-forge
dependencies:
  - python=3.12.12
  - ydata-profiling
  - numpy
  - pandas
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn
prefix: /Users/edmundzhou/miniforge3/envs/Student_Performance_ML
